### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by SplendidAlakey** [Faboslav/friends-and-foes-beekeeper-hut#1]
### Minecraft version information

1.19.2

### Mod loader information

Quilt

### Mod loader version information

0.18.1-beta.26 (also reproducible on 0.17.8)

### Mod version information

1.0.0

### Reproduction Steps

1. Install the mod and run the game

### Crash Report and latest.log

Crash: https://gist.github.com/SplendidAlakey/815e43b6fad06e7b6e63937341a192a5#file-crash-log

Latest: https://gist.github.com/SplendidAlakey/815e43b6fad06e7b6e63937341a192a5#file-latest-log

**Comment by Faboslav** [comment]
Thank your for the report, i will try to make a fix tommorow :).

**Comment by Faboslav** [comment]
Should be fixed with the 1.2.0 release.
